version: '3.7'

services:
  jenkins:
    # image: ahl/jenkins:latest
    # alternatively, I've switched to the blueocean enabled version of Jenkins
    # this doesn't require a custom image, it's smaller and contains the 
    # embedded docker client
    # image: jenkinsci/blueocean:latest
    build: ./build_def_jenkins
    image: ahl/jenkins:v1
    user: root
    networks:
        tc-net:
          aliases: 
            - "orchestrate"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      # run Docker from the host system when the container calls it. Note, Docker is stll 
      # required in the jenkins container
      - /var/run/docker.sock:/var/run/docker.sock
      # adding a bind for the Gradle build so the Gradle container can run the code. 
      # the Gradle container isn't specified here because the Jenkins agent bootstraps the build
      - spring_boot_demo:/home/project
      # for kubernetes yamls
      - kube_yamls:/kube/deploy

    container_name: jenkins

  db: 
    image: postgres:10.7
    networks:
      tc-net:
        aliases: 
          - "db"
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
      POSTGRES_USER_FILE: /run/secrets/postgres-user
      PGDATA: /var/lib/postgresql/data/pgdata
    secrets:
      - postgres-user
      - postgres-passwd
    volumes:
      # contains the database(s) on the host
      - postgres_home:/var/lib/postgresql/data/pgdata
    container_name: postgres
  
  sonarqube: 
    build: ./build_def_sonar
    image: ahl/sonar:v1
    # user: sonarqube
    networks:
      tc-net:
        aliases: 
          - "analyze"
    ports: 
      - "9000:9000"
      - "9092:9092"
    secrets:
      # using postgres creds because Sonar connects to postgres
       - postgres-passwd
       - postgres-user
    volumes:
      # currently projecting conf, but not using any custom values yet
      - sonar_home_conf:/opt/sonarqube/conf
      - sonar_home_data:/opt/sonarqube/data
      - sonar_home_ext:/opt/sonarqube/extensions
      - sonar_home_plug:/opt/sonarqube/lib/bundled-plugins
    container_name: sonar

  nexus:
    image: sonatype/nexus3:latest
    networks:
      tc-net:
        aliases:
          - "package-repo"
    ports:
      - "8088:8081"
    volumes:
      # - ./nexus_home/nexus_data:/nexus-data
      - nexus_home:/nexus-data

    container_name: nexus

  git:
    image: gogs/gogs
    networks:
      tc-net:
        aliases:
          - "git-repo"
    ports:
      - "10022:22"
      - "10080:3000"
    volumes:
      # - ./git_home/var/gogs:/data
      - git_home:/data
    container_name: gogs

  nginx:
    build: ./build_def_nginx
    image: ahl/nginx:v1
    networks:
      tc-net:
        aliases: 
          - "reverse-proxy"
    ports:
       - "18445:18445"
       - "18446:18446"
       - "18447:18447"
    
    # to debug nginx:
    command: [nginx-debug, '-g', 'daemon off;']
    
    container_name: nginx

    # to resolve for automating setup: 
    # had to manually create gogs db in postgres
    # had to manually run install at http://localhost:10080 and select postgres w/gogs db
    # and postgres admin logon - see creds above in postgres section. Postgres at db:5432
    # had to create account in gogs when browsing to http://localhost:10080. First time, 
    # gogs went to http://localhost:3000, which failed

networks:
  tc-net:

volumes:
  jenkins_home:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${PWD}/jenkins_home"
  spring_boot_demo:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${PWD}/spring-boot-demo"
  kube_yamls:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${PWD}/kube_yamls"
  kube_yamls:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${PWD}/kube_yamls"
  postgres_home:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${PWD}/postgres_home/data"
  sonar_home_conf:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${PWD}/sonar_home/conf"
  sonar_home_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${PWD}/sonar_home/data"
  sonar_home_ext:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${PWD}/sonar_home/extensions"
  sonar_home_plug:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${PWD}/sonar_home/lib/bundled-plugins"
  nexus_home:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${PWD}/nexus_home/nexus_data"
  git_home:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${PWD}/git_home/var/gogs"

secrets:
  postgres-user:
    file: ./secrets/postgres_usr.txt
  postgres-passwd:
    file: ./secrets/postgres_password.txt
  sonarqube-user:
    file: ./secrets/sonarqube_usr.txt
  sonarqube-passwd:
    file: ./secrets/sonarqube_password.txt