FROM openjdk
VOLUME /tmp
# WORKDIR /home/gradle/project
# ARG JAR_FILE

# COPY ${JAR_FILE} app.jar
# Trying this as the preferred form...
# COPY ["${JAR_FILE}" "/app.jar"]

# RUN ["/bin/bash", "-c", "cp ${JAR_FILE} app.jar"]
# RUN /bin/bash -c 'pwd'
# RUN /bin/bash -c 'echo $PWD'
# RUN ["/bin/bash", "-c", "echo ${PWD}"]

# ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
# EXPOSE 8888